name = "igreja-nova-cidade"
main = "backend/worker.py"
compatibility_date = "2026-09-30"
compatibility_flags = ["python_workers"]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "igreja-nova-cidade"
database_id = "d5a339fe-6204-428a-ab06-be70b4849943"
migrations_dir = "drizzle"
