import { LineChart, Line, PieChart, Pie, Cell, ResponsiveContainer, CartesianGrid, XAxis, YAxis, Tooltip, Legend } from 'recharts';
import { analyzeFinances } from './finance-analysis';
import { money } from './finance';
const names = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const colors = ['#6358c9','#0c8a68','#c57c14','#c94d56','#397bab','#99704d','#7c588e'];
const percentage = (value: number) => value.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
const tooltipMoney = (value: unknown) => money(Number(value)*100);
export function FinancialInsights({data,year,month,ministry}:{data: Record<string, any[]>;year:number;month:number;ministry:string}) {
 const a=analyzeFinances(data,year,month,ministry);
 const period = month ? `${names[month-1]} de ${year}` : `ano de ${year}`;
 const previous = a.previousMonth ? `${names[a.previousMonth-1]} de ${a.previousYear}` : `ano de ${a.previousYear}`;
 const points=a.monthly.map(m=>({name:names[m.month-1].slice(0,3),Entradas:m.income===null?null:m.income/100,Saídas:m.spent===null?null:m.spent/100,Resultado:m.net===null?null:m.net/100}));
 const categoryPoints=a.categories.slice(0,6).map(c=>({name:c.name,value:c.amount/100}));
 if(a.categories.length>6) categoryPoints.push({name:"Outras categorias",value:a.categories.slice(6).reduce((sum,c)=>sum+c.amount,0)/100});
 const movements=[{name:'Entradas',value:a.income/100},{name:'Saídas',value:a.spent/100}].filter(c=>c.value>0);
 const change=(delta:number,base:number)=>`${delta>0?'aumentaram':delta<0?'diminuíram':'se mantiveram'}${delta ? ` ${money(Math.abs(delta))}${base>0?` (${percentage(Math.abs(delta)/base*100)})`:''}`:''}`;
 return <>
  <section className="panel analysis-panel">
   <div className="panel-heading"><div><h2>Análise automática e equilíbrio financeiro</h2><p>{period} · somente os lançamentos do escopo autorizado e selecionado</p></div></div>
   {!a.hasCurrent ? <p className="finance-note">Sem movimentações registradas neste período. Não há dados suficientes para avaliar superávit, déficit ou tendências.</p> : <div className="insights">
    <div className={`insight ${a.net<0?'red':'green'}`}><strong>{a.net<0?'Déficit: gastos maiores que entradas':a.net>0?'Superávit: entradas maiores que gastos':'Entradas e gastos equilibrados'}</strong><p>Entradas de {money(a.income)}, despesas de {money(a.spent)} e resultado de {money(a.net)}. {a.coverage!==null && `As entradas cobrem ${percentage(a.coverage)} das despesas.`}</p></div>
    <div className="insight"><strong>Altas e baixas em relação a {previous}</strong><p>{a.hasPrevious ? `As entradas ${change(a.incomeDelta,a.previousIncome)} e as despesas ${change(a.spentDelta,a.previousSpent)}. A comparação usa apenas valores registrados; períodos incompletos podem distorcer a leitura.` : 'O período anterior não tem movimentações registradas. Ainda não há base para afirmar aumento ou queda.'}</p></div>
    <div className="insight"><strong>{a.deficit?'Onde revisar para buscar equilíbrio':'Como avaliar novos investimentos'}</strong><p>{a.deficit ? `Para equilibrar este período, seria necessário reduzir despesas ou aumentar entradas em ${money(a.deficit)}. Se todas as despesas fossem ajustáveis, isso equivaleria a uma redução média de ${percentage(a.reductionPercent)}. Revise primeiro as maiores categorias abaixo, verificando contratos, prioridades e gastos que podem ser adiados. A concentração de gastos, sozinha, não comprova desperdício.` : `Confira o saldo acumulado, as reservas de pedidos aprovados e as obrigações ainda não lançadas antes de investir. Resultado positivo no período não significa que todo o valor esteja livre para gastar.`}</p>
    {a.categories.length>0 && <ul className="analysis-categories">{a.categories.slice(0,3).map(c=><li key={c.name}><strong>{c.name}</strong>: {money(c.amount)} ({percentage(c.amount/a.spent*100)} das despesas).</li>)}</ul>}</div>
    <div className="insight"><strong>Pontos de atenção no ano</strong><p>{a.deficitMonths.length ? `Meses com gastos acima das entradas: ${a.deficitMonths.map(m=>names[m.month-1]).join(', ')}.` : 'Nenhum mês com movimentações registradas apresentou gastos acima das entradas.'} {a.peakIncome!==null && a.monthly.some(m=>(m.income||0)>0) && `Maior entrada mensal: ${names[a.peakIncome-1]}.`} {a.peakExpense!==null && a.monthly.some(m=>(m.spent||0)>0) && `Maior gasto mensal: ${names[a.peakExpense-1]}.`}</p></div>
   </div>}
   <p className="finance-note">Análise descritiva dos valores cadastrados, sem previsão de receitas nem decisões automáticas de corte. Valores não lançados não são considerados. Orçamento autorizado e dinheiro em caixa são medidas diferentes.</p>
  </section>
  <section className="panel analysis-panel"><div className="panel-heading"><div><h2>Linhas · evolução mensal e resultado</h2><p>{year} · verde: entradas; vermelho: saídas; roxo: resultado</p></div></div>
   {a.monthly.some(m=>m.recorded) ? <div className="flow-chart"><ResponsiveContainer width="100%" height={290}><LineChart data={points} margin={{left:8,right:20,top:12,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis width={90} tickFormatter={v=>money(Number(v)*100)}/><Tooltip formatter={tooltipMoney}/><Legend/><Line type="linear" dataKey="Entradas" stroke="#0c8a68" strokeWidth={2} connectNulls={false}/><Line type="linear" dataKey="Saídas" stroke="#c94d56" strokeWidth={2} connectNulls={false}/><Line type="linear" dataKey="Resultado" stroke="#6358c9" strokeWidth={2} connectNulls={false}/></LineChart></ResponsiveContainer></div> : <p className="finance-note">Sem movimentações no ano selecionado.</p>}
   <p className="finance-note">Linha de resultado abaixo de zero indica déficit no mês; acima de zero indica superávit. Meses sem lançamentos ficam sem ponto, pois falta de informação não comprova equilíbrio.</p>
   <details className="analysis-details"><summary>Ver valores mensais e balanço</summary><div className="table-scroll"><table><thead><tr><th>Mês</th><th>Entradas</th><th>Saídas</th><th>Resultado</th></tr></thead><tbody>{a.monthly.map(m=><tr key={m.month}><td>{names[m.month-1]}</td><td>{m.recorded?money(m.income!):'Sem lançamentos'}</td><td>{m.recorded?money(m.spent!):'—'}</td><td className={(m.net||0)<0?'negative':''}>{m.recorded?money(m.net!):'—'}</td></tr>)}</tbody></table></div></details>
  </section>
  <div className="overview-grid analysis-panel">
   <section className="panel"><div className="panel-heading"><div><h2>Pizza · gastos por categoria</h2><p>{period}</p></div></div>{categoryPoints.length ? <ResponsiveContainer width="100%" height={280}><PieChart><Pie data={categoryPoints} dataKey="value" nameKey="name" cx="50%" cy="45%" outerRadius={85}>{categoryPoints.map((c,i)=><Cell key={c.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={tooltipMoney}/><Legend/></PieChart></ResponsiveContainer> : <p className="finance-note">Sem despesas para distribuir por categoria.</p>}<p className="finance-note">Cada fatia representa a participação da categoria no total gasto. Após as seis maiores categorias, as demais são agrupadas em “Outras categorias”. Fatias maiores indicam concentração e ajudam a escolher o que revisar, sem indicar automaticamente onde cortar.</p></section>
   <section className="panel"><div className="panel-heading"><div><h2>Rosca · entradas versus saídas</h2><p>{period}</p></div></div>{movements.length ? <ResponsiveContainer width="100%" height={280}><PieChart><Pie data={movements} dataKey="value" nameKey="name" innerRadius={55} outerRadius={85} cx="50%" cy="45%">{movements.map(c=><Cell key={c.name} fill={c.name==='Entradas'?'#0c8a68':'#c94d56'}/>)}</Pie><Tooltip formatter={tooltipMoney}/><Legend/></PieChart></ResponsiveContainer> : <p className="finance-note">Sem entradas ou despesas neste período.</p>}<p className="finance-note">Compara o volume de dinheiro recebido e gasto. A parte vermelha maior que a verde indica gastos acima das entradas; confira o resultado de {money(a.net)}. A rosca não representa o saldo disponível nem o consumo do orçamento.</p></section>
  </div>
 </>;
}
